---
abstract: 'Wikibase data type cloning helper.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
  Test::Shared::Fixture::Wikibase::Datatype::Form::Wikidata::DogCzechSingular: 0
  Test::Shared::Fixture::Wikibase::Datatype::Item::Wikidata::Dog: 0
  Test::Shared::Fixture::Wikibase::Datatype::Lexeme::Wikidata::DogCzechNoun: 0
  Test::Shared::Fixture::Wikibase::Datatype::Mediainfo::Commons::ImageOfHuman: 0
  Test::Shared::Fixture::Wikibase::Datatype::MediainfoSnak::Commons::Depicts::Human: 0
  Test::Shared::Fixture::Wikibase::Datatype::MediainfoStatement::Commons::Depicts::Human: 0
  Test::Shared::Fixture::Wikibase::Datatype::Property::Wikidata::InstanceOf: 0
  Test::Shared::Fixture::Wikibase::Datatype::Reference::Wikidata::ReferenceURL: 0
  Test::Shared::Fixture::Wikibase::Datatype::Sense::Wikidata::Dog: 0
  Test::Shared::Fixture::Wikibase::Datatype::Snak::Wikidata::GivenName::Michal: 0
  Test::Shared::Fixture::Wikibase::Datatype::Statement::Wikidata::GivenName::Michal: 0
  Test::Shared::Fixture::Wikibase::Datatype::Value::Item::Wikidata::Dog: 0
  Unicode::UTF8: 0
  Wikibase::Datatype::Value::Globecoordinate: 0
  Wikibase::Datatype::Value::Item: 0
  Wikibase::Datatype::Value::Lexeme: 0
  Wikibase::Datatype::Value::Monolingual: 0
  Wikibase::Datatype::Value::Property: 0
  Wikibase::Datatype::Value::Quantity: 0
  Wikibase::Datatype::Value::Sense: 0
  Wikibase::Datatype::Value::String: 0
  Wikibase::Datatype::Value::Time: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wikibase-Datatype-Clone
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Inspector: 0
  Class::Utils: 0.03
  Error::Pure: 0.15
  List::Util: 1.33
  Readonly: 0
  Scalar::Util: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Wikibase-Datatype-Clone/issues
  homepage: https://github.com/michal-josef-spacek/Wikibase-Datatype-Clone
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Wikibase-Datatype-Clone
version: '0.01'
